import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const CSS = `*{margin:0;padding:0;box-sizing:border-box}body{font-family:Arial,sans-serif;font-size:13px;color:#1C2B32;padding:48px;max-width:820px;margin:0 auto;line-height:1.6}.header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:32px;padding-bottom:20px;border-bottom:3px solid #0A0A0A}.logo{font-size:20px;font-weight:700;letter-spacing:2px;color:#D4522A}.doc-type{font-size:11px;color:#7A9098;text-transform:uppercase;letter-spacing:1px;margin-top:4px}.badge{padding:5px 12px;border-radius:4px;font-size:11px;font-weight:700;border:1px solid}.badge-green{background:#E8F4F0;color:#2E7D60;border-color:#2E7D60}.badge-orange{background:#FDF0ED;color:#D4522A;border-color:#D4522A}.badge-grey{background:#F4F8F7;color:#7A9098;border-color:#C8D5D2}.section{margin-bottom:24px}.section-title{font-size:10px;font-weight:700;color:#7A9098;text-transform:uppercase;letter-spacing:1px;margin-bottom:10px;padding-bottom:6px;border-bottom:1px solid #E8F0EE}.grid-2{display:grid;grid-template-columns:1fr 1fr;gap:16px}.grid-3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px}.label{font-size:10px;color:#7A9098;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:3px}.value{font-size:13px;color:#0A0A0A;font-weight:500}.sub{font-size:11px;color:#7A9098;margin-top:2px}.body-text{background:#F4F8F7;border:1px solid #E8F0EE;border-radius:6px;padding:14px;line-height:1.7;white-space:pre-wrap;font-size:13px}.card{background:#F4F8F7;border:1px solid #E8F0EE;border-radius:8px;padding:16px;margin-bottom:10px}.sig-block{background:#F4F8F7;border:1px solid #E8F0EE;border-radius:6px;padding:14px;margin-bottom:10px}.sig-name{font-size:15px;font-weight:700;color:#0A0A0A;margin-bottom:4px}.sig-detail{font-size:11px;color:#4A5E64;margin-bottom:2px}.signed{color:#2E7D60;font-weight:600}.unsigned{color:#D4522A}.audit-block{background:#0A0A0A;border-radius:8px;padding:20px;margin-top:24px}.audit-block .title{font-size:10px;color:rgba(216,228,225,0.4);text-transform:uppercase;letter-spacing:1px;margin-bottom:14px}.audit-entry{border-top:1px solid rgba(255,255,255,0.08);padding:10px 0}.audit-event{font-size:12px;color:rgba(216,228,225,0.9);font-weight:600;margin-bottom:3px}.audit-meta{font-size:11px;color:rgba(216,228,225,0.4);margin-bottom:1px}.notice{background:#F4F8F7;border:1px solid #E8F0EE;border-radius:6px;padding:14px 16px;font-size:11px;color:#4A5E64;line-height:1.7;margin-bottom:20px}.milestone-row{border:1px solid #E8F0EE;border-radius:6px;margin-bottom:8px;overflow:hidden}.milestone-header{background:#F4F8F7;padding:10px 14px;display:flex;justify-content:space-between;align-items:center}.milestone-body{padding:10px 14px}.issue-row{border-left:3px solid #D4522A;padding:10px 14px;margin-bottom:8px;background:#FFF8F6;border-radius:0 6px 6px 0}.product-row{background:#F4F8F7;border:1px solid #E8F0EE;border-radius:6px;padding:10px 14px;margin-bottom:6px}.dialogue-q{border-left:3px solid;padding:12px 14px;margin-bottom:14px;border-radius:0 6px 6px 0}.footer{font-size:10px;color:#9AA5AA;text-align:center;margin-top:32px;padding-top:12px;border-top:1px solid #E8F0EE}`

const fmt = (d?: string|null) => d ? new Date(d).toLocaleString('en-AU',{timeZone:'Australia/Perth',dateStyle:'long',timeStyle:'short'}) : '—'
const fmtDate = (d?: string|null) => d ? new Date(d).toLocaleDateString('en-AU',{timeZone:'Australia/Perth',day:'numeric',month:'long',year:'numeric'}) : '—'

const pageHeader = (docType: string, title: string, badge?: string, badgeClass='badge-grey') => `<div class="header"><div><div class="logo">STEADYHAND</div><div class="doc-type">${docType}</div></div><div style="text-align:right"><div style="font-size:16px;font-weight:700;color:#0A0A0A;margin-bottom:6px">${title}</div>${badge?`<span class="badge ${badgeClass}">${badge}</span>`:''}</div></div>`
const pageFooter = (jobId: string, docType: string) => `<div class="footer">SH-${jobId.slice(0,8).toUpperCase()} &nbsp;·&nbsp; ${docType} &nbsp;·&nbsp; steadyhandtrade.app &nbsp;·&nbsp; Generated ${fmtDate(new Date().toISOString())} AWST</div>`
const etaNotice = () => `<div class="notice"><strong>Electronic Transactions Act Compliance:</strong> This document was generated by Steadyhand in accordance with the <em>Electronic Transactions Act 1999</em> (Cth) and <em>Electronic Transactions Act 2011</em> (WA). Steadyhand is not a party to any agreement between the parties named and does not adjudicate disputes.</div>`
const wrap = (docType: string, title: string, body: string, badge?: string, badgeClass?: string) => `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>${title} — Steadyhand</title><style>${CSS}</style></head><body>${pageHeader(docType,title,badge,badgeClass)}${body}${pageFooter(title,docType)}</body></html>`

const partiesSection = (job: any) => `<div class="section"><div class="section-title">Parties</div><div class="grid-2"><div><div class="label">Client</div><div class="value">${job.client?.full_name||'—'}</div><div class="sub">${job.client?.email||''}</div></div><div><div class="label">Trade Business</div><div class="value">${job.tradie?.business_name||'—'}</div>${job.tradie?.licence_number?`<div class="sub">Licence: ${job.tradie.licence_number}</div>`:''}<div class="sub">${(job.tradie as any)?.profile?.email||''}</div></div></div></div>`
const jobMetaSection = (job: any) => `<div class="section"><div class="section-title">Job Details</div><div class="grid-3"><div><div class="label">Job ID</div><div class="value">SH-${job.id?.slice(0,8).toUpperCase()}</div></div><div><div class="label">Location</div><div class="value">${job.suburb||'—'}, WA</div></div><div><div class="label">Trade</div><div class="value">${job.trade_category||'—'}</div></div><div><div class="label">Status</div><div class="value">${(job.status||'').replace(/_/g,' ')}</div></div><div><div class="label">Created</div><div class="value">${fmtDate(job.created_at)}</div></div><div><div class="label">Property type</div><div class="value">${job.property_type||'Residential'}</div></div></div></div>`

async function genRequest(jobId: string) {
  const {data:job} = await supabase.from('jobs').select('*, client:profiles!jobs_client_id_fkey(full_name,email), tradie:tradie_profiles(business_name,licence_number,abn,profile:profiles(email))').eq('id',jobId).single()
  if(!job) return null
  const {data:qrs} = await supabase.from('quote_requests').select('*, tradie:tradie_profiles(business_name)').eq('job_id',jobId)
  const body = `${jobMetaSection(job)}${partiesSection(job)}<div class="section"><div class="section-title">Job Description</div><div class="body-text">${job.description||'No description provided'}</div></div>${job.special_requirements?`<div class="section"><div class="section-title">Special Requirements</div><div class="body-text">${job.special_requirements}</div></div>`:''}<div class="notice">This document records the initial job request as submitted by the client. No work should proceed until a scope agreement has been signed by both parties.</div>`
  return wrap('Initial Job Request', job.title||'Job Request', body, `Created ${fmtDate(job.created_at)}`, 'badge-grey')
}

async function genConsult(jobId: string) {
  const {data:job} = await supabase.from('jobs').select('*, client:profiles!jobs_client_id_fkey(full_name,email), tradie:tradie_profiles(business_name,licence_number,profile:profiles(email))').eq('id',jobId).single()
  if(!job) return null
  const {data:assessments} = await supabase.from('site_assessments').select('*').eq('job_id',jobId).order('created_at',{ascending:true})
  const clientA = assessments?.find((a:any)=>a.submitted_by==='client'||a.role==='client')
  const tradieA = assessments?.find((a:any)=>a.submitted_by==='tradie'||a.role==='tradie')
  const renderA = (a:any,role:string) => {
    if(!a) return `<div class="card"><p style="color:#7A9098;font-style:italic">${role} has not yet submitted consult notes.</p></div>`
    const notes = typeof a.notes==='string'?JSON.parse(a.notes||'{}'):(a.notes||{})
    return `<div class="card"><div class="label" style="margin-bottom:8px">${role} — submitted ${fmt(a.submitted_at||a.created_at)}</div>${notes.observations?`<div style="margin-bottom:10px"><div class="label">Observations</div><div class="body-text" style="font-size:12px">${notes.observations}</div></div>`:''}${notes.concerns?`<div style="margin-bottom:10px"><div class="label">Concerns</div><div class="body-text" style="font-size:12px">${notes.concerns}</div></div>`:''}${notes.free_text||a.free_text?`<div><div class="label">Notes</div><div class="body-text" style="font-size:12px">${notes.free_text||a.free_text}</div></div>`:''}${a.acknowledged_at?`<div style="margin-top:10px;font-size:11px;color:#2E7D60">✓ Acknowledged ${fmt(a.acknowledged_at)}</div>`:''}</div>`
  }
  const bothAck = clientA?.acknowledged_at && tradieA?.acknowledged_at
  const body = `${jobMetaSection(job)}${partiesSection(job)}<div class="section"><div class="section-title">Client Consult Notes</div>${renderA(clientA,'Client')}</div><div class="section"><div class="section-title">Tradie Consult Notes</div>${renderA(tradieA,'Tradie')}</div><div class="notice">Consult notes are recorded independently by each party and locked before being shared — creating a tamper-proof baseline record of site conditions before any agreement is signed.</div>`
  return wrap('Site Consult Record', job.title||'Consult Record', body, bothAck?'✓ Mutually acknowledged':'Pending acknowledgement', bothAck?'badge-green':'badge-orange')
}

async function genScope(jobId: string) {
  const {data:job} = await supabase.from('jobs').select('*, client:profiles!jobs_client_id_fkey(full_name,email), tradie:tradie_profiles(business_name,licence_number,abn,profile:profiles(email))').eq('id',jobId).single()
  if(!job) return null
  const {data:scopes} = await supabase.from('scope_agreements').select('*').eq('job_id',jobId).order('version',{ascending:false})
  const scope = scopes?.[0]; if(!scope) return null
  const {data:dialogues} = await supabase.from('dialogue_responses').select('*').eq('job_id',jobId).order('question_num',{ascending:true})
  const {data:quotes} = await supabase.from('quotes').select('*').eq('job_id',jobId).eq('status','accepted').limit(1)
  const quote = quotes?.[0]
  const fullyExecuted = scope.client_signed_at && scope.tradie_signed_at
  const auditLog:any[] = scope.audit_log||[]
  const DCOLS = ['#2E7D60','#2E6A8F','#6B4FA8','#C07830']
  const body = `${jobMetaSection(job)}${partiesSection(job)}<div class="section"><div class="section-title">Agreement Details</div><div class="grid-3"><div><div class="label">Version</div><div class="value">v${scope.version||1}</div></div><div><div class="label">Agreed Total</div><div class="value">${scope.quote_total||quote?.total_price?'$'+Number(scope.quote_total||quote?.total_price).toLocaleString('en-AU'):'As per quote'}</div></div><div><div class="label">Warranty</div><div class="value">${job.warranty_period||90} days</div></div></div></div>${scope.inclusions?`<div class="section"><div class="section-title">Inclusions</div><div class="body-text">${Array.isArray(scope.inclusions)?scope.inclusions.join('\n'):scope.inclusions}</div></div>`:''}${scope.exclusions?`<div class="section"><div class="section-title">Exclusions</div><div class="body-text">${Array.isArray(scope.exclusions)?scope.exclusions.join('\n'):scope.exclusions}</div></div>`:''}<div class="section"><div class="section-title">Electronic Signatures</div><div class="sig-block"><div class="sig-name">${job.client?.full_name||'Client'}</div><div class="sig-detail">${job.client?.email||'—'}</div>${scope.client_signed_at?`<div class="sig-detail signed">✓ Signed ${fmt(scope.client_signed_at)} AWST</div>`:'<div class="sig-detail unsigned">⚠ Not yet signed</div>'}</div><div class="sig-block"><div class="sig-name">${job.tradie?.business_name||'Contractor'}</div><div class="sig-detail">${(job.tradie as any)?.profile?.email||'—'}</div>${scope.tradie_signed_at?`<div class="sig-detail signed">✓ Signed ${fmt(scope.tradie_signed_at)} AWST</div>`:'<div class="sig-detail unsigned">⚠ Not yet signed</div>'}</div></div>${dialogues&&dialogues.length>0?`<div class="section"><div class="section-title">Pre-signing Dialogue Record</div>${dialogues.map((r:any,i:number)=>`<div class="dialogue-q" style="border-color:${DCOLS[i%DCOLS.length]};background:${DCOLS[i%DCOLS.length]}08"><div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.5px;color:${DCOLS[i%DCOLS.length]};margin-bottom:6px">${['Price & payment','Scope & inclusions','Licence & compliance','Warranty & defects'][i]||'Dimension '+(i+1)}</div>${r.tradie_response?`<div style="background:white;border-radius:6px;padding:8px 10px;margin-bottom:6px"><div style="font-size:10px;font-weight:700;color:#0A0A0A;margin-bottom:3px">TRADIE</div><p style="font-size:12px;color:#1C2B32">${r.tradie_response}</p></div>`:''}${r.client_response?`<div style="background:white;border-radius:6px;padding:8px 10px"><div style="font-size:10px;font-weight:700;color:#2E6A8F;margin-bottom:3px">CLIENT</div><p style="font-size:12px;color:#1C2B32">${r.client_response}</p></div>`:''}</div>`).join('')}</div>`:''}${auditLog.length?`<div class="audit-block"><div class="title">Signature Audit Trail</div>${auditLog.map((e:any)=>`<div class="audit-entry"><div class="audit-event">${e.event==='client_signed'?'✓ Client signed':'✓ Contractor signed'}</div><div class="audit-meta">${e.email||e.user_id}</div><div class="audit-meta">${fmt(e.timestamp)} AWST &nbsp;·&nbsp; IP: ${e.ip}</div></div>`).join('')}</div>`:''}${etaNotice()}`
  return wrap('Scope Agreement', job.title||'Scope', body, fullyExecuted?'✓ Fully Executed':scope.client_signed_at||scope.tradie_signed_at?'Partially Signed':'Draft', fullyExecuted?'badge-green':'badge-orange')
}

async function genMilestones(jobId: string) {
  const {data:job} = await supabase.from('jobs').select('*, client:profiles!jobs_client_id_fkey(full_name,email), tradie:tradie_profiles(business_name,licence_number,profile:profiles(email))').eq('id',jobId).single()
  if(!job) return null
  const {data:milestones} = await supabase.from('milestones').select('*').eq('job_id',jobId).order('created_at',{ascending:true})
  const total = (milestones||[]).reduce((s:number,m:any)=>s+Number(m.amount||0),0)
  const paid = (milestones||[]).filter((m:any)=>m.status==='approved').reduce((s:number,m:any)=>s+Number(m.amount||0),0)
  const SC:Record<string,string>={pending:'#C07830',submitted:'#2E6A8F',approved:'#2E7D60',disputed:'#D4522A'}
  const body = `${jobMetaSection(job)}${partiesSection(job)}<div class="section"><div class="section-title">Payment Summary</div><div class="grid-3"><div><div class="label">Total contract</div><div class="value">$${total.toLocaleString('en-AU')}</div></div><div><div class="label">Paid to date</div><div class="value" style="color:#2E7D60">$${paid.toLocaleString('en-AU')}</div></div><div><div class="label">Outstanding</div><div class="value" style="color:#C07830">$${(total-paid).toLocaleString('en-AU')}</div></div></div></div><div class="section"><div class="section-title">Milestones</div>${(milestones||[]).map((m:any,i:number)=>`<div class="milestone-row"><div class="milestone-header"><div><div class="value">Milestone ${i+1}${m.description?' — '+m.description:''}</div><div class="sub">$${Number(m.amount||0).toLocaleString('en-AU')}</div></div><span style="font-size:12px;font-weight:600;color:${SC[m.status]||'#7A9098'}">${(m.status||'pending').toUpperCase()}</span></div><div class="milestone-body">${m.submitted_at?`<div style="font-size:11px;color:#2E6A8F;margin-bottom:2px">→ Submitted ${fmt(m.submitted_at)}</div>`:''}${m.approved_at?`<div style="font-size:11px;color:#2E7D60">✓ Approved ${fmt(m.approved_at)}</div>`:''}</div></div>`).join('')}</div>${etaNotice()}`
  return wrap('Milestone & Payment Record', job.title||'Milestones', body, `${(milestones||[]).filter((m:any)=>m.status==='approved').length}/${(milestones||[]).length} approved`, 'badge-grey')
}

async function genWarranty(jobId: string) {
  const {data:job} = await supabase.from('jobs').select('*, tradie:tradie_profiles(business_name,licence_number,abn,preferred_products,profile:profiles(email)), client:profiles!jobs_client_id_fkey(full_name,email)').eq('id',jobId).single()
  if(!job) return null
  const {data:scope} = await supabase.from('scope_agreements').select('inclusions,total_price').eq('job_id',jobId).order('created_at',{ascending:false}).limit(1).maybeSingle()
  const {data:issues} = await supabase.from('warranty_issues').select('*').eq('job_id',jobId).order('created_at',{ascending:true})
  const products = Array.isArray(job.tradie?.preferred_products)?job.tradie.preferred_products:[]
  const active = job.warranty_ends_at?new Date(job.warranty_ends_at)>new Date():false
  const body = `${jobMetaSection(job)}${partiesSection(job)}<div class="section"><div style="background:#E8F4F0;border:2px solid #2E7D60;border-radius:8px;padding:16px 20px;display:flex;justify-content:space-between;align-items:center"><div><div style="font-size:32px;font-weight:700;color:#2E7D60">${job.warranty_period||90} days</div><div style="font-size:12px;color:#7A9098">Workmanship warranty commenced ${fmtDate(job.signoff_at)}</div></div><div style="text-align:right"><div style="font-size:12px;color:#7A9098;margin-bottom:4px">Expires</div><div style="font-size:16px;font-weight:600">${fmtDate(job.warranty_ends_at)}</div><div style="font-size:12px;font-weight:600;color:${active?'#2E7D60':'#D4522A'};margin-top:4px">${active?'✓ Active':'✗ Expired'}</div></div></div></div>${products.length>0?`<div class="section"><div class="section-title">Products Installed</div>${products.map((p:any)=>`<div class="product-row"><div class="value">${p.name||'—'}${p.brand?' · '+p.brand:''}</div><div class="sub">${p.warranty_years?`Mfr warranty: ${p.warranty_years==='lifetime'?'Lifetime':p.warranty_years+' yr'}`:'Mfr warranty: not specified'}${p.notes?' · '+p.notes:''}</div>${p.reason?`<div style="font-size:11px;color:#4A5E64;font-style:italic;margin-top:4px">"${p.reason}"</div>`:''}</div>`).join('')}</div>`:''}<div class="notice"><strong>Important:</strong> This warranty covers workmanship only. Product and manufacturer warranties are governed by each manufacturer's terms. This document and your signed scope agreement constitute your primary evidence for any claim.</div>`
  return wrap('Warranty Certificate', job.title||'Warranty', body, active?'✓ Active':'Expired', active?'badge-green':'badge-orange')
}

async function genAudit(jobId: string) {
  const {data:job} = await supabase.from('jobs').select('*, client:profiles!jobs_client_id_fkey(full_name,email), tradie:tradie_profiles(business_name,licence_number,abn,profile:profiles(email))').eq('id',jobId).single()
  if(!job) return null
  const [
    {data:qrs},{data:assessments},{data:scopes},{data:quotes},{data:milestones},{data:issues},{data:messages},{data:variations}
  ] = await Promise.all([
    supabase.from('quote_requests').select('*').eq('job_id',jobId),
    supabase.from('site_assessments').select('*').eq('job_id',jobId),
    supabase.from('scope_agreements').select('*').eq('job_id',jobId).order('version',{ascending:true}),
    supabase.from('quotes').select('*').eq('job_id',jobId).order('version',{ascending:true}),
    supabase.from('milestones').select('*').eq('job_id',jobId).order('created_at',{ascending:true}),
    supabase.from('warranty_issues').select('*').eq('job_id',jobId),
    supabase.from('job_messages').select('*').eq('job_id',jobId).order('created_at',{ascending:true}),
    supabase.from('variations').select('*').eq('job_id',jobId),
  ])
  const events:Array<{ts:string,event:string,detail:string,cat:string}>=[]
  const push=(ts:string|null|undefined,event:string,detail:string,cat:string)=>{if(ts)events.push({ts,event,detail,cat})}
  push(job.created_at,'Job request created',`${job.title} · ${job.trade_category} · ${job.suburb}`,'request')
  ;(qrs||[]).forEach((q:any)=>{push(q.requested_at||q.created_at,'Tradie invited',q.tradie_id?`ID: ${q.tradie_id.slice(0,8)}`:'External invite','shortlist');if(q.qr_status==='accepted')push(q.updated_at,'Tradie accepted','','shortlist');if(q.qr_status==='declined')push(q.updated_at,'Tradie declined','','shortlist')})
  ;(assessments||[]).forEach((a:any)=>{push(a.created_at,'Consult notes submitted',`By: ${a.submitted_by||a.role||'unknown'}`,'consult');if(a.acknowledged_at)push(a.acknowledged_at,'Consult notes acknowledged','','consult')})
  ;(quotes||[]).forEach((q:any)=>{push(q.created_at,`Estimate submitted (v${q.version||1})`,`$${Number(q.total_price).toLocaleString()} · ${q.status}`,'quote')})
  ;(scopes||[]).forEach((s:any)=>{push(s.created_at,`Scope created (v${s.version||1})`,'','agreement');if(s.client_signed_at)push(s.client_signed_at,'Scope signed by client','','agreement');if(s.tradie_signed_at)push(s.tradie_signed_at,'Scope signed by contractor','','agreement')})
  ;(milestones||[]).forEach((m:any,i:number)=>{push(m.created_at,`Milestone ${i+1} created`,`$${Number(m.amount||0).toLocaleString()}`,'delivery');if(m.submitted_at)push(m.submitted_at,`Milestone ${i+1} submitted`,'','delivery');if(m.approved_at)push(m.approved_at,`Milestone ${i+1} approved`,`$${Number(m.amount||0).toLocaleString()}`,'delivery')})
  push(job.signoff_at,'Job signed off',`Warranty: ${job.warranty_period||90} days`,'sign-off')
  push(job.warranty_ends_at,'Warranty period expires','','warranty')
  ;(issues||[]).forEach((i:any)=>{push(i.created_at,'Warranty issue raised',i.title,'warranty');if(i.resolved_at)push(i.resolved_at,'Warranty issue resolved',i.title,'warranty')})
  ;(messages||[]).forEach((m:any)=>{push(m.created_at,'Message',(m.body||'').substring(0,80),'message')})
  events.sort((a,b)=>new Date(a.ts).getTime()-new Date(b.ts).getTime())
  const CC:Record<string,string>={request:'#2E7D60',shortlist:'#2E6A8F',consult:'#9B6B9B',quote:'#6B4FA8',agreement:'#C07830',delivery:'#1A6B5A','sign-off':'#D4522A',warranty:'#2E7D60',message:'#7A9098'}
  const body = `${jobMetaSection(job)}${partiesSection(job)}<div class="section"><div class="section-title">Summary</div><div class="grid-3"><div><div class="label">Total events</div><div class="value">${events.length}</div></div><div><div class="label">Milestones</div><div class="value">${(milestones||[]).length}</div></div><div><div class="label">Warranty issues</div><div class="value">${(issues||[]).length}</div></div></div></div><div class="section"><div class="section-title">Complete Chronological Record (${events.length} events)</div>${events.map((e,i)=>`<div style="display:flex;gap:14px;margin-bottom:12px;${i<events.length-1?'padding-bottom:12px;border-bottom:1px solid #F4F8F7':''}"><div style="width:4px;border-radius:2px;background:${CC[e.cat]||'#C8D5D2'};flex-shrink:0"></div><div style="flex:1"><div style="display:flex;justify-content:space-between;gap:8px"><div style="font-size:13px;font-weight:600;color:#0A0A0A">${e.event}</div><div style="font-size:10px;color:#9AA5AA;flex-shrink:0;white-space:nowrap">${fmt(e.ts)}</div></div>${e.detail?`<div style="font-size:11px;color:#7A9098;margin-top:2px">${e.detail}</div>`:''}<div style="font-size:10px;color:${CC[e.cat]||'#C8D5D2'};text-transform:uppercase;letter-spacing:0.5px;margin-top:3px">${e.cat}</div></div></div>`).join('')}</div>${etaNotice()}`
  return wrap('Electronic Audit Trail', job.title||'Audit Trail', body, `${events.length} events`, 'badge-grey')
}

export async function GET(request: NextRequest, { params }: { params: { type: string } }) {
  const jobId = request.nextUrl.searchParams.get('job_id')
  if(!jobId) return NextResponse.json({error:'job_id required'},{status:400})
  const generators: Record<string,(id:string)=>Promise<string|null>> = {
    request:genRequest, consult:genConsult, scope:genScope,
    milestones:genMilestones, warranty:genWarranty, audit:genAudit,
  }
  const gen = generators[params.type]
  if(!gen) return NextResponse.json({error:`Unknown type. Valid: ${Object.keys(generators).join(', ')}`},{status:400})
  const html = await gen(jobId)
  if(!html) return NextResponse.json({error:'Not found or insufficient data'},{status:404})
  const names: Record<string,string> = {request:'job-request',consult:'consult-record',scope:'scope-agreement',milestones:'milestone-record',warranty:'warranty-certificate',audit:'audit-trail'}
  const shortId = jobId.slice(0,8).toUpperCase()
  return new NextResponse(html,{status:200,headers:{'Content-Type':'text/html; charset=utf-8','Content-Disposition':`attachment; filename="${names[params.type]||params.type}-SH-${shortId}.html"`}})
}
